[tool.ruff]
# 검사 대상 디렉토리 제한
src = ["src"]  # src 디렉토리만 검사

# 한 줄의 최대 길이
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "W"]  # E: 스타일, F: Pyflakes, W: 경고
ignore = ["E501"]         # E501: 한 줄 길이 초과 무시